[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "wrf_clc"
version = "0.1.0"
description = "Evaluation of WRF simulation of coastal low clouds and fog"

dependencies = [
    "numpy",
    "xarray",
    "pandas",
]

[tool.setuptools.packages.find]
where = ["."]
